services:
  aeroprint_host:
    build:
      context: ./deploy/host
      dockerfile: Dockerfile
    container_name: aeroprint_host
    privileged: true
    shm_size: 2g  # Added to prevent shared memory issues
    volumes:
      - ./src:/home/aeroprint_user/aeroprint/src
    network_mode: host
    ipc: host
    command: tail -f /dev/null