name: aeroprint
base: core20 
version: '1.0.1'
summary: ROS2 Application for UDRI DTC AeroPrint Project
description: |
  This app enables automated control of a ModalAI Starling and automatic 3D data collection and processing, as well as automated 3D printing with a Prusa MK4.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ros2-connection:
    plugin: colcon
    # source: https://github.com/kuederleR/aeroprint.git
    # source-branch: deployed-1.0.1
    source: .
    source-branch: master
    stage-packages: [ros-foxy-ros2launch]
  # aeroprint-app:
  #   plugin: dump
  #   source: .
  #   source-branch: master
    
apps:
  host:    
    command: opt/ros/foxy/bin/ros2 launch starling starling_launch.py
    extensions: [ros2-foxy]
  starling:
    command: opt/ros/foxy/bin/ros2 launch host host_launch.py
    extensions: [ros2-foxy]