#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'host','console_scripts','pc_processor'
__requires__ = 'host'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('host', 'console_scripts', 'pc_processor')()
    )
