name: ros-foxy-pyqt5-tensorflow
version: '0.1'
summary: ROS Foxy project with PyQt5 GUI and TensorFlow
description: |
  This snap includes a ROS Foxy project with a PyQt5 GUI and TensorFlow integration.
grade: devel
confinement: devmode

base: core20

parts:
  ros-foxy:
    plugin: colcon
    source: .
    build-packages:
      - python3-colcon-common-extensions
    stage-packages:
      - ros-foxy-ros2launch
      # - python3-pyqt5
      # - python3-tensorflow

  pyqt5-gui:
    plugin: python
    source: .
    stage-packages:
      - python3-pyqt5

  tensorflow:
    plugin: python
    source: .
    requirements: 
      - tensorflow

apps:
  ros-foxy-pyqt5-tensorflow:
    command: opt/ros/foxy/bin/ros2 launch host host_test_launch.py
    plugs:
      - network
      - network-bind
      - home
      - removable-media
      - system-files
    extensions: [ros2-foxy]
