# Simple workflow for deploying static content to GitHub Pages
name: Compile

# runs-on: self-hosted

on:
  # Runs on pushes targeting the default branch
  push:
    branches: []

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "compile"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  ccp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: C++ Check
        run: | 
          pip install pylama
          pylama --linters=cppcheck src/arduino
  
  ros:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ROS Test
        run: |
          bash aeroprint_setup.bash
          source /opt/ros/foxy/setup.bash
          colcon build
     